linters-settings:
  errcheck:
    # Exclude functions that are safe to ignore or in legacy code
    exclude-functions:
      - (hash.Hash).Write
      - (*net/http.Header).Set
      - (io.Closer).Close
      - regexp.MatchString
      - io.ReadAll
      - encoding/json.Marshal
      - net/http.NewRequest
    # Check for blank assignments to error return values
    check-blank: true
    # Don't check type assertions (they can panic instead)
    check-type-assertions: false

linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
  disable:
    - errcheck  # Temporarily disabled due to pre-existing code issues

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - node_modules

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  # Maximum count of issues with the same text
  max-same-issues: 0
